_wandb:
    value:
        cli_version: 0.21.0
        e:
            gvrjq70mncw8oiizuelkkc0eafrnyrsw:
                args:
                    - --exp-dir
                    - ./exp
                    - --exp-name
                    - oulu_45
                    - --modality
                    - video
                    - --root-dir
                    - /workspace/auto-avsr/oulu
                    - --train-file
                    - 45/train.csv
                    - --val-file
                    - 45/val.csv
                    - --test-file
                    - 45/test.csv
                    - --gpus
                    - "1"
                    - --max-epochs
                    - "700"
                    - --num-nodes
                    - "1"
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 14
                cpu_count_logical: 28
                cudaVersion: "12.6"
                disk:
                    /:
                        total: "1081101176832"
                        used: "721470885888"
                email: mgmgkeis@gmail.com
                executable: /opt/conda/bin/python
                git:
                    commit: 182b62837773ab01052d4ac21ef1d2203ea7d267
                    remote: https://github.com/mpc001/auto_avsr.git
                gpu: NVIDIA GeForce RTX 3060
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      memoryTotal: "12884901888"
                      name: NVIDIA GeForce RTX 3060
                      uuid: GPU-a741c6c7-ff71-634a-ba79-71ae02026c9f
                host: b1e9ad8b05ee
                memory:
                    total: "25196359680"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.27
                program: /workspace/auto-avsr/train.py
                python: CPython 3.10.8
                root: .
                startedAt: "2025-07-18T08:16:01.000127Z"
                writerId: gvrjq70mncw8oiizuelkkc0eafrnyrsw
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.10.8
        t:
            "1":
                - 1
                - 9
                - 41
                - 103
                - 106
            "2":
                - 1
                - 9
                - 41
                - 103
                - 106
            "3":
                - 7
                - 13
                - 66
            "4": 3.10.8
            "5": 0.21.0
            "12": 0.21.0
            "13": linux-x86_64
ckpt_path:
    value: null
ctc_weight:
    value: 0.1
debug:
    value: false
exp_dir:
    value: ./exp
exp_name:
    value: oulu_45
gpus:
    value: 1
group_name:
    value: null
lr:
    value: 0.001
max_epochs:
    value: 700
max_frames:
    value: 1600
modality:
    value: video
num_nodes:
    value: 1
pretrained_model_path:
    value: null
root_dir:
    value: /workspace/auto-avsr/oulu
slurm_job_id:
    value: "0"
test_file:
    value: 45/test.csv
train_file:
    value: 45/train.csv
train_num_buckets:
    value: 400
transfer_encoder:
    value: false
transfer_frontend:
    value: false
val_file:
    value: 45/val.csv
warmup_epochs:
    value: 5
weight_decay:
    value: 0.03
