_wandb:
    value:
        cli_version: 0.21.0
        e:
            7seed4m4kqr84yuyky5mbx1i8xhmms2x:
                args:
                    - --exp-dir
                    - ./exp
                    - --exp-name
                    - oulu_front
                    - --modality
                    - video
                    - --root-dir
                    - /workspace/auto-avsr/oulu
                    - --train-file
                    - train.csv
                    - --val-file
                    - val.csv
                    - --test-file
                    - test.csv
                    - --gpus
                    - "1"
                    - --max-epochs
                    - "1000"
                    - --num-nodes
                    - "1"
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 14
                cpu_count_logical: 28
                cudaVersion: "12.6"
                disk:
                    /:
                        total: "1081101176832"
                        used: "636994400256"
                email: mgmgkeis@gmail.com
                executable: /opt/conda/bin/python
                git:
                    commit: 182b62837773ab01052d4ac21ef1d2203ea7d267
                    remote: https://github.com/mpc001/auto_avsr.git
                gpu: NVIDIA GeForce RTX 3060
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      memoryTotal: "12884901888"
                      name: NVIDIA GeForce RTX 3060
                      uuid: GPU-a741c6c7-ff71-634a-ba79-71ae02026c9f
                host: b1e9ad8b05ee
                memory:
                    total: "25196355584"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.27
                program: /workspace/auto-avsr/train.py
                python: CPython 3.10.8
                root: .
                startedAt: "2025-07-09T15:59:35.576820Z"
                writerId: 7seed4m4kqr84yuyky5mbx1i8xhmms2x
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.10.8
        t:
            "1":
                - 1
                - 9
                - 41
                - 103
                - 106
            "2":
                - 1
                - 9
                - 41
                - 103
                - 106
            "3":
                - 7
                - 13
                - 66
            "4": 3.10.8
            "5": 0.21.0
            "12": 0.21.0
            "13": linux-x86_64
